### ISSUE TITLE
In case oc-version fails, tailor will still continue or end without meaningful message denoting failed artifact

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/tailor#217] opened 2020-08-06 17:05 UTC
Also, it appears that tailor will not return a non-zero value.

```
    amazon-ebs: apply-sonarqube-build:
    amazon-ebs: ~/opendevstack/ods-core/sonarqube/ocp-config ~/opendevstack/ods-core
==> amazon-ebs: --> oc version
==> amazon-ebs: --> oc version
==> amazon-ebs: --> oc version
==> amazon-ebs: --> Client and server version could not be detected properly, got: oc v3.11.0+62803d0-1
==> amazon-ebs: kubernetes v1.11.0+d4cacc0
==> amazon-ebs: features: Basic-Auth GSSAPI Kerberos SPNEGO
==> amazon-ebs:
==> amazon-ebs: Server https://127.0.0.1:8443
==> amazon-ebs: kubernetes v1.11.0+d4cacc0
==> amazon-ebs:
==> amazon-ebs: --> Version information is incomplete: client (v3.11) and server (?) detected. This is likely due to a local cluster setup. If not, this could lead to incorrect behaviour.
==> amazon-ebs: --> oc project ods --short
==> amazon-ebs: --> Client and server version could not be detected properly, got: oc v3.11.0+62803d0-1
```
Coming from here.. 
https://github.com/opendevstack/tailor/blob/master/pkg/cli/oc_version.go#L61

The issue is we see this in 3/20 concurrent builds.. so this is Not stably reproducable

**Comment by michaelsauter** [comment] 2020-08-07 06:32
@georgfedermann I am not sure what the issue is exactly?

It looks like the intended behaviour to me. Local clusters (started with `oc cluster up`) do not report the server version, which Tailor wants to use to ensure that client and server match. I don't know why this is the case, but Tailor proceeds even though it cannot detect the versions properly. Tailor will only fail if it can detect both client and server version, and they do not match. The reasoning is that detection should work in real-life clusters, where the consequences of errors due to mismatch are higher.

**Comment by michaelsauter** [comment] 2020-08-07 07:30
Closing as this works as intended.

**Closed by michaelsauter** 2020-08-07 07:30 UTC
